steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/${_RUN_SERVICE_NAME}", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/${_RUN_SERVICE_NAME}"]

  - id: "deploy to google run"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - ${_RUN_SERVICE_NAME}
      - '--image'
      - 'gcr.io/${_PROJECT_ID}/${_RUN_SERVICE_NAME}'
      - '--region'
      - ${_REGION}
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _REGION: europe-west1
  _RUN_SERVICE_NAME: cra-cloud-run
  _PROJECT_ID: gatsby-wh330-0

images:
  - "gcr.io/${_PROJECT_ID}/${_RUN_SERVICE_NAME}"
